spring:
  datasource:
    username: dbuser
    password: pass
    url: jdbc:mysql://localhost:3306/disney
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web: debug
    org.hibernate: ERROR
